name: BukkitUpdater
main: zauberstuhl.BukkitUpdater.BukkitUpdater
version: 0.2.5
author: zauberstuhl
description: none
commands:
  u2d:
    description: display new updates and more
    aliases:
    usage: /<command> [update|unsupported|help] <PluginName>