name: BukkitUpdater
main: de.enco.BukkitUpdater.BukkitUpdater
version: 2.0.1.5
author: 3nc0_de,davr
website: http://www.3nc0.de/
description: |
  The plugin updated outdated plugins, if there is a static link on the database.
database: false
commands:
  u2d:
    description: updated outdated plugins and more
    usage: |
      /<command> - Shows updated plugin(s)
      /<command> update - Will trigger manual the update process
      /<command> search [<plugin>|<description>] - You can search after new plugins (Resource: dev.bukkit.org)
      /<command> install <plugin> - Install completely new plugins via a single command
      /<command> ignore <PluginName> - Add/Remove a plugin from the blacklist
      /<command> ignore list - List all ignored plugins
      /<command> help - Display the help page
permissions:
  BukkitUpdater.*:
    description: Gives access to all BukkitUpdater commands
    default: op
    children:
      BukkitUpdater.info: true
      BukkitUpdater.update: true
      BukkitUpdater.install: true
      BukkitUpdater.ignore: true
      BukkitUpdater.reload: true
  BukkitUpdater.info:
    description: Allows you to list informations about updated/searched plugins
  BukkitUpdater.update:
    description: Will trigger manual the update process
  BukkitUpdater.install:
    description: Install completely new plugins via a single command
  BukkitUpdater.ignore:
    description: Add/Remove a plugin from the blacklist
