name: BukkitUpdater
main: de.enco.BukkitUpdater.BukkitUpdater
version: 2.0.1.0
author: 3nc0_de
website: http://www.3nc0.de/
description: |
  The plugin updated outdated plugins, if there is a static link on the database.
database: false
commands:
  u2d:
    description: updated outdated plugins and more
    usage: |
      /<command> - Shows updated plugin(s)
      /<command> ignore <PluginName> - Add/Remove a plugin from the blacklist
      /<command> ignore list - List all ignored plugins
      /<command> reload <PluginName> - Reload the plugin e.g. after a update
      /<command> help - Display the help page
permissions:
  BukkitUpdater.*:
    description: Gives access to all BukkitUpdater commands
    default: op
    children:
      BukkitUpdater.info: true
      BukkitUpdater.ignore: true
      BukkitUpdater.reload: true
  BukkitUpdater.info:
    description: Allows you to list informations about updated plugins
  BukkitUpdater.ignore:
    description: Add/Remove a plugin from the blacklist
  BukkitUpdater.reload:
    description: Allows you to reload single plugins
